name: BetterShop
main: com.nhksos.jjfs85.BetterShop.BetterShop
version: 1.6.5.6
website: http://github.com/BetterShop/BetterShop
author: jascotty2 and jjfs85 (and lologarithm)
description: >
             BetterShop is a command-based shop for Bukkit.
             It uses iConomy or BOSEcon for the economic backbone,
             and can use Permissions, Help, and MinecraftIM
commands:
  shop:
    description: Command Alias / Admin Command
    usage: /<command> [check|list|buy|sell|add|remove|[re]load|help]
    aliases: [bettershop,bshop]
  shopcheck:
    description: Check prices for an item
    usage: /<command> [item]
    aliases: [sc,scheck]
  shoplist:
    description: Lists prices for the shop
    usage: /<command> <page>
    aliases: [sl,slist]
  shopitems:
    description: show listing of items in shop, without prices
    usage: /<command>
    aliases: [sitems]
  shopbuy:
    description: Buy an item for the price in the shop
    usage: /<command> [item] [amount]
    aliases: [buy,sbuy]
  shopbuyall:
    description: Buy all of an item that you can hold
    usage: /<command> [item]
    aliases: [buyall,sbuyall]
  shopbuystack:
    description: Buy a stack of an item for the price in the shop
    usage: /<command> [item]
    aliases: [buystack,sbuystack,sbuys,buys]
  shopsell:
    description: Sell an item for the price in the shop
    usage: /<command> [item] <amount>
    aliases: [sell,ssell]
  shopsellall:
    description: Sell all of item from your inventory
    usage: /<command> [item]
    aliases: [sellall]
  shopsellstack:
    description: Sell a stack of an item to the shop
    usage: /<command> [item] <amount>
    aliases: [sellstack,ssellstack,sells,ssells]
  shopadd:
    description: Add an item to or update an item in the price list
    usage: /<command> [item] [buy-price] [sell-price]
    aliases: [sadd]
  shopremove:
    description: Remove an item from the price list
    usage: /<command> [item]
    aliases: [sremove]
  shopload:
    description: reload prices from pricelist database
    usage: /<command>
    aliases: [sload]
  shophelp:
    description: Lists available commands
    usage: /<command>
    aliases: [shelp]
  shoplistkits:
    description: Lists available kits
    usage: /<command> <page>
    aliases: [shopkits,skits]
  shopbuyagain:
    description: repeat last purchase
    usage: /<command>
    aliases: [sbuyagain, buyagain, sba]
  shopsellagain:
    description: repeat last sale
    usage: /<command>
    aliases: [ssellagain, sellagain, ssa]
